# Generated by Django 4.1.5 on 2023-01-14 18:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('phoneNumber', models.CharField(max_length=9)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pesel', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('phoneNumber', models.CharField(max_length=9)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pesel', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=45)),
                ('houseNumber', models.IntegerField()),
                ('flatNumber', models.IntegerField(blank=True, null=True)),
                ('postcode', models.CharField(max_length=11)),
                ('placeName', models.CharField(max_length=45)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(choices=[('19,99zł', 19.99), ('25zł', 25), ('33zł', 33)])),
                ('zone', models.CharField(choices=[('Pływalnia', 'Pływalnia'), ('SPA', 'SPA'), ('Siłownia', 'Siłownia')], max_length=45)),
                ('dateOfPurchase', models.DateTimeField(default=datetime.datetime(2023, 1, 14, 19, 36, 19, 580585), editable=False)),
                ('dateOfEnd', models.DateTimeField(blank=True, editable=False, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.client')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField(blank=True, editable=False, null=True)),
                ('description', models.CharField(choices=[('1 zmiana', '1 zmiana'), ('2 zmiana', '2 zmiana')], max_length=12)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.worker')),
            ],
        ),
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=45)),
                ('houseNumber', models.IntegerField()),
                ('flatNumber', models.IntegerField(blank=True, null=True)),
                ('postcode', models.CharField(max_length=11)),
                ('placeName', models.CharField(max_length=45)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.client')),
            ],
        ),
    ]
