# Generated by Django 4.1.5 on 2023-01-14 19:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='pesel',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phoneNumber',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.client'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dateOfPurchase',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 14, 20, 37, 19, 748040), editable=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.CharField(choices=[('19.99', '19.99zł'), ('25', '25zł'), ('33', '33zł')], max_length=6),
        ),
        migrations.AlterField(
            model_name='worker',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='pesel',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phoneNumber',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='workeraddress',
            name='worker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.worker'),
        ),
    ]
