# Generated by Django 4.2 on 2023-04-17 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_ticket_dateofpurchase_alter_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='description',
            field=models.CharField(choices=[('1 zmiana', '1 zmiana'), ('2 zmiana', '2 zmiana')], default=('1 zmiana', '1 zmiana'), max_length=12),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dateOfPurchase',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 17, 15, 31, 2, 416906)),
        ),
    ]
